

---
experiment:
  root_name: test 
  name: test
data:
  key: 1hot-sequence #sequence 
   # if you insert a new sequence in the student's dictionary, change the key here
ml:
  nfolds: 2 #10
  # test_size: 0.1
  epochs: 1 #30
  oversampler: 
    oversampling_factor: 1.5
    oversampling_col:
      - label
      - language
    rebalancing_mode: baseline # can be "rebalance", "100unbalanced", "100balanced", "5050balanced"
    number_categories: 2cat # can be '2cat' or '4cat'
    sample_size: 400
  splitter:
    stratifier_col: 
      - stratifier_column
seeds:
  splitter: 219
  oversampler: 13
  model: 139
  numpy: 36
...

